name: Deploy to GitHub Pages (manual)

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve latest successful Prebuild run-id
        id: resolve_run
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            // Find latest successful run of the prebuild workflow by file name
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'prebuild.yml',
              status: 'success',
              per_page: 1
            });
            if (!runs.data.workflow_runs.length) {
              core.setFailed('No successful Prebuild run found. Run the Prebuild workflow first.');
              return;
            }
            const runId = runs.data.workflow_runs[0].id;
            core.info(`Using Prebuild run-id: ${runId}`);
            core.setOutput('run_id', String(runId));
      - name: Download artifact from Prebuild
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist
          run-id: ${{ steps.resolve_run.outputs.run_id }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
